package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static cloud.autotests.helpers.DriverHelper.getConsoleLogs;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("test 01")
    void generatedTest() {
        step("open https://habr.com/ru/company/jugru/blog/337386/", () -> {
            // todo just add selenium action
        });

        step("click button login", () -> {
            // todo just add selenium action
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://habr.com/ru/company/jugru/blog/337386/'", () ->
            open("https://habr.com/ru/company/jugru/blog/337386/"));

        step("Page title should have text 'Allure 2: тест-репорты нового поколения / Блог компании JUG Ru Group / Хабр'", () -> {
            String expectedTitle = "Allure 2: тест-репорты нового поколения / Блог компании JUG Ru Group / Хабр";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...'")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://habr.com/ru/company/jugru/blog/337386/'", () ->
            open("https://habr.com/ru/company/jugru/blog/337386/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}